# Generated by Django 2.2.5 on 2019-10-03 21:27

from django.db import migrations, models
import sqlpaths.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('checksum', models.CharField(max_length=40, validators=[sqlpaths.models.HexDigestValidator()])),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('execute_timestamp', models.DateTimeField(blank=True, null=True)),
                ('execute_status', models.IntegerField(validators=[sqlpaths.models.NonNegativeValidator()])),
            ],
            options={
                'db_table': 'sqlpaths_migrations',
                'unique_together': {('path', 'checksum')},
            },
        ),
    ]
